use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::model::NoteRecord;

fn group_key(note: &NoteRecord) -> &'static str {
    match note.namespace.as_str() {
        "project" => "Projects",
        "topic" => "Topics",
        "person" => "People",
        "system" => "System",
        "global" => "Global",
        _ => "Other",
    }
}

fn render_note(note: &NoteRecord) -> String {
    let kind = if note.canonical {
        "canonical"
    } else {
        note.note_type.as_str()
    };

    format!(
        "- **{}** [{}] {}  \n  - `{}`\n",
        note.title, note.status, kind, note.path
    )
}

fn namespace_dir(namespace: &str) -> &'static str {
    match namespace {
        "project" => "projects",
        "topic" => "topics",
        "person" => "people",
        _ => "",
    }
}

pub fn write_global_index(root: &Path, notes: &[NoteRecord]) -> std::io::Result<()> {
    let mut groups: BTreeMap<&str, Vec<&NoteRecord>> = BTreeMap::new();

    for note in notes {
        groups.entry(group_key(note)).or_default().push(note);
    }

    let mut output = String::from(
        "# Memory Index\n\n\
         > Generated by the deterministic Markdown indexer. Do not edit manually.\n\n",
    );

    for section in ["System", "Projects", "Topics", "People", "Global", "Other"] {
        output.push_str(&format!("## {section}\n\n"));

        if let Some(items) = groups.get(section) {
            let mut sorted = items.clone();

            sorted.sort_by(|a, b| {
                b.canonical.cmp(&a.canonical).then_with(|| {
                    a.title
                        .to_ascii_lowercase()
                        .cmp(&b.title.to_ascii_lowercase())
                })
            });

            for note in sorted {
                output.push_str(&render_note(note));
            }

            output.push('\n');
        } else {
            output.push_str("_None._\n\n");
        }
    }

    fs::write(root.join("INDEX.md"), output)
}

pub fn write_namespace_indexes(root: &Path, notes: &[NoteRecord]) -> std::io::Result<()> {
    for namespace in ["project", "topic", "person"] {
        let directory = namespace_dir(namespace);

        if directory.is_empty() {
            continue;
        }

        let mut items = notes
            .iter()
            .filter(|note| note.namespace == namespace)
            .collect::<Vec<_>>();

        items.sort_by(|a, b| {
            b.canonical.cmp(&a.canonical).then_with(|| {
                a.title
                    .to_ascii_lowercase()
                    .cmp(&b.title.to_ascii_lowercase())
            })
        });

        let title = match namespace {
            "project" => "Projects",
            "topic" => "Topics",
            "person" => "People",
            _ => "Other",
        };

        let mut output = format!(
            "# {title} Index\n\n\
             > Generated by the deterministic Markdown indexer. Do not edit manually.\n\n"
        );

        if items.is_empty() {
            output.push_str("_None._\n");
        } else {
            for note in items {
                output.push_str(&render_note(note));
            }
        }

        let directory_path = root.join(directory);

        std::fs::create_dir_all(&directory_path)?;

        fs::write(directory_path.join("INDEX.md"), output)?;
    }

    Ok(())
}

fn push_timestamp(output: &mut String, timestamp: Option<&String>, kind: &str, note: &NoteRecord) {
    if let Some(timestamp) = timestamp {
        output.push_str(&format!(
            "- `{timestamp}` **{kind}**: {}  \n  `{}`\n",
            note.title, note.path
        ));
    }
}

pub fn write_timeline(root: &Path, notes: &[NoteRecord]) -> std::io::Result<()> {
    let mut events: Vec<(String, &'static str, &NoteRecord)> = Vec::new();

    for note in notes {
        for (kind, timestamp) in [
            ("captured_at", note.captured_at.as_ref()),
            ("occurred_at", note.occurred_at.as_ref()),
            ("valid_from", note.valid_from.as_ref()),
            ("valid_to", note.valid_to.as_ref()),
            ("due_at", note.due_at.as_ref()),
            ("updated_at", note.updated_at.as_ref()),
        ] {
            if let Some(timestamp) = timestamp {
                events.push((timestamp.clone(), kind, note));
            }
        }
    }

    events.sort_by(|a, b| {
        a.0.cmp(&b.0)
            .then_with(|| a.1.cmp(b.1))
            .then_with(|| a.2.path.cmp(&b.2.path))
    });

    let mut output = String::from(
        "# Timeline\n\n\
         > Generated navigation index. Source timestamps remain authoritative.\n\n",
    );

    if events.is_empty() {
        output.push_str("_No dated notes yet._\n");
    } else {
        for (timestamp, kind, note) in events {
            push_timestamp(&mut output, Some(&timestamp), kind, note);
        }
    }

    fs::write(root.join("TIMELINE.md"), output)
}
